### ISSUE TITLE
pip install - no matching distribution found for pyras

### ISSUE THREAD

**Issue by solomonvimal** [PyHydro/pyras#5]
![image](https://cloud.githubusercontent.com/assets/2102394/7376382/68cc5dbe-edad-11e4-9ebe-9353c872a0dd.png)

**Comment by solomonvimal** [comment]
I installed win32 libraries required for this: the hard way.

**Comment by goanpeca** [comment]
pywin32 is not automatically installed by pip at this point...

**Comment by goanpeca** [comment]
Why not just simply download the repository and run everything from it

This software is in beta release still
